name: Build - Resume Analyzer Web App

on:
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

env:
DOTNET_VERSION: '9.0.x'
PROJECT_PATH: './src/ResumeAnalyzer.Blazor'

jobs:
  build:
    runs-on: windows-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
  
    - name: Restore
      run: dotnet restore
  
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
    - name: Publish Blazor App
      run: |
        dotnet publish \
          ${{ env.PROJECT_PATH }} \
          -c Release \
          -o publish
  
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: blazor-app
        path: publish/wwwroot